package com.example.newsapp.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF005FAF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD5E3FF)
val LightOnPrimaryContainer = Color(0xFF001C3A)
val LightInversePrimary = Color(0xFFA8C8FF)
val LightSecondary = Color(0XFF3F6964)
val LightOnSecondary = Color(0XFFFFFFFF)
val LightSecondaryContainer = Color(0XFFC0EBE2)
val LightOnSecondaryContainer = Color(0XFF00201D)
val LightBackground = Color(0xFFE8EBF0)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFF8F9FC)
val LightOnSurface = Color(0xFF1A1C1E)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F4F7)
val LightSurfaceContainer = Color(0xFFEEF0F3)
val LightSurfaceContainerHigh = Color(0xFFE8EAED)
val LightSurfaceContainerHighest = Color(0xFFE2E4E8)
val LightInverseSurface = Color(0xFF303033)
val LightInverseOnSurface = Color(0xFFF1F0F4)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C6CF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)


val DarkPrimary = Color(0xFFA8C8FF)
val DarkOnPrimary = Color(0xFF00315E)
val DarkPrimaryContainer = Color(0xFF004786)
val DarkOnPrimaryContainer = Color(0xFFD5E3FF)
val DarkInversePrimary = Color(0xFF005FAF)

val DarkSecondary = Color(0XFFA5CEC7)
val DarkOnSecondary = Color(0XFF0B3732)
val DarkSecondaryContainer = Color(0XFF274F4A)
val DarkOnSecondaryContainer = Color(0XFFC0EBE2)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE3E2E6)
val DarkSurface = Color(0xFF25282D)
val DarkOnSurface = Color(0xFFE3E2E6)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkSurfaceContainerLowest = Color(0xFF202225)
val DarkSurfaceContainerLow = Color(0xFF292B2E)
val DarkSurfaceContainer = Color(0xFF32353A)
val DarkSurfaceContainerHigh = Color(0xFF3D4045)
val DarkSurfaceContainerHighest = Color(0xFF484B50)
val DarkInverseSurface = Color(0xFFE1E2E6)
val DarkInverseOnSurface = Color(0xFF1A1C1E)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
